package infiniq.demo;

import java.util.HashMap;
import java.util.Map;

public class KnowledgeBase {

    private final Map<String, String> data = new HashMap<>();

    public void loadDefaults() {
        data.put("Who developed you?", "Lokesh ReddyRishik Rao");
data.put("Which animal is called the king of the jungle?", "Lion");
data.put("How many days are there in a week?", "7 days");
data.put("Which is the fastest land animal?", "Cheetah");
data.put("What is the color of the sky?", "Blue");
data.put("How many letters are there in the English alphabet?", "26");
data.put("Which shape has three sides?", "Triangle");
data.put("Which fruit is known as the king of fruits?", "Mango");
data.put("Which animal gives us milk?", "Cow");
data.put("Which bird cannot fly?", "Ostrich");
data.put("Which is the largest animal?", "Blue Whale");
data.put("Which insect has colorful wings?", "Butterfly");
data.put("How many months are there in a year?", "12 months");
data.put("Which sense organ helps us see?", "Eyes");
data.put("Which organ helps us hear?", "Ears");
data.put("Which animal has a long trunk?", "Elephant");
data.put("Which animal gives us wool?", "Sheep");
data.put("Which food makes your bones strong?", "Milk");
data.put("What do plants need to grow?", "Sunlight, water and air");
data.put("Which planet do we live on?", "Earth");
data.put("How many colors are there in a rainbow?", "7");
data.put("Which animal is man's best friend?", "Dog");
data.put("Which animal hops?", "Kangaroo");
data.put("Which bird says caw caw?", "Crow");
data.put("What do bees make?", "Honey");
data.put("Which shape is round?", "Circle");
data.put("Which fruit keeps the doctor away?", "Apple");
data.put("Which bird is the national bird of India?", "Peacock");
data.put("Which is the tallest animal?", "Giraffe");
data.put("Which vehicle runs on rails?", "Train");
data.put("Which organ helps us smell?", "Nose");
data.put("Which organ helps us taste?", "Tongue");
data.put("Which flower is known as the king of flowers?", "Rose");
data.put("Which vegetable is called the king of vegetables?", "Brinjal");
data.put("Which festival is known as the festival of lights?", "Diwali");
data.put("Which fruit has a crown on top?", "Pineapple");
data.put("Which animal loves bananas?", "Monkey");
data.put("Which bird can mimic human voice?", "Parrot");
data.put("Which animal has black and white stripes?", "Zebra");
data.put("Which insect makes a buzzing sound?", "Bee");
data.put("What do we use to write?", "Pencil");
data.put("Which month has 28 or 29 days?", "February");
data.put("What do plants give us?", "Oxygen");
data.put("Which animal lives in igloos?", "Polar Bear");
data.put("Which fruit is yellow and long?", "Banana");
data.put("Which shape has four equal sides?", "Square");
data.put("What do cows eat?", "Grass");
data.put("Which bird lays the largest egg?", "Ostrich");
data.put("Which animal sleeps during winter?", "Bear");
data.put("What do fish use to breathe?", "Gills");
data.put("What do we wear on our feet?", "Shoes");
data.put("Who is the father of our nation?", "Mahatma Gandhi");
data.put("What is the capital of India?", "New Delhi");
data.put("Which is the largest continent?", "Asia");
data.put("Which is the smallest continent?", "Australia");
data.put("Which river is the longest in the world?", "Nile");
data.put("What is the national flower of India?", "Lotus");
data.put("What is the national fruit of India?", "Mango");
data.put("What is the national animal of India?", "Tiger");
data.put("Who invented the telephone?", "Alexander Graham Bell");
data.put("Who invented the bulb?", "Thomas Edison");
data.put("Which gas do plants release?", "Oxygen");
data.put("Which gas do humans exhale?", "Carbon dioxide");
data.put("Which is the largest ocean?", "Pacific Ocean");
data.put("Which planet is known as the red planet?", "Mars");
data.put("Which planet is known as the blue planet?", "Earth");
data.put("Which is the smallest planet?", "Mercury");
data.put("Which planet is closest to the sun?", "Mercury");
data.put("Which is the largest planet?", "Jupiter");
data.put("What is the study of plants called?", "Botany");
data.put("What is the study of animals called?", "Zoology");
data.put("What is the chemical formula of water?", "H2O");
data.put("Which vitamin do we get from sunlight?", "Vitamin D");
data.put("Which blood group is known as the universal donor?", "O Negative");
data.put("Which blood group is known as the universal recipient?", "AB Positive");
data.put("Which is the hardest natural substance?", "Diamond");
data.put("Which is the softest mineral?", "Talc");
data.put("Which is the longest bone in the human body?", "Femur");
data.put("How many bones are in a human body?", "206");
data.put("Which is the largest organ in the human body?", "Skin");
data.put("Which organ purifies blood?", "Kidney");
data.put("Which organ pumps blood?", "Heart");
data.put("Which organ controls the body?", "Brain");
data.put("Which metal is liquid at room temperature?", "Mercury");
data.put("Which gas is essential for breathing?", "Oxygen");
data.put("Which country is known as the land of rising sun?", "Japan");
data.put("Which country is known as the land of white elephants?", "Thailand");
data.put("Which country is known as the land of midnight sun?", "Norway");
data.put("Which is the smallest country in the world?", "Vatican City");
data.put("Which is the largest country in the world?", "Russia");
data.put("What is the capital of Japan?", "Tokyo");
data.put("What is the capital of China?", "Beijing");
data.put("What is the capital of Sri Lanka?", "Colombo");
data.put("What is the capital of France?", "Paris");
data.put("What is the capital of Germany?", "Berlin");
data.put("What is the capital of Nepal?", "Kathmandu");
data.put("What is the capital of Pakistan?", "Islamabad");
data.put("Who discovered electricity?", "Benjamin Franklin");
data.put("Which metal is used in thermometers?", "Mercury");
data.put("What is the full form of CPU?", "Central Processing Unit");
data.put("What is the full form of RAM?", "Random Access Memory");
data.put("What is the full form of ROM?", "Read Only Memory");
data.put("What is the full form of USB?", "Universal Serial Bus");
data.put("What is the full form of WWW?", "World Wide Web");
data.put("Which ocean is the smallest?", "Arctic Ocean");
data.put("Which ocean is the deepest?", "Pacific Ocean");
data.put("Which is the largest freshwater lake?", "Lake Superior");
data.put("What is the national song of India?", "Vande Mataram");
data.put("Who wrote the national anthem of India?", "Rabindranath Tagore");
data.put("What is the national currency of India?", "Rupee");
data.put("Which festival is known as the festival of colors?", "Holi");
data.put("What is the color of a banana?", "Yellow");
data.put("What is the color of an apple?", "Red");
data.put("How many wheels does a bicycle have?", "Two");
data.put("How many wheels does a car have?", "Four");
data.put("What is the color of milk?", "White");
data.put("Which animal purrs?", "Cat");
data.put("Which animal has a shell?", "Tortoise");
data.put("Which bird hoots?", "Owl");
data.put("Which bird is green in color?", "Parrot");
data.put("Which fruit is green outside and red inside?", "Watermelon");
data.put("Which fruit has many seeds inside?", "Papaya");
data.put("What do we drink to stay healthy?", "Water");
data.put("What do we breathe?", "Air");
data.put("Which star gives us light?", "Sun");
data.put("What do we wear on rainy days?", "Raincoat");
data.put("What do we use to cut paper?", "Scissors");
data.put("Which vegetable is orange in color?", "Carrot");
data.put("Which fruit is sour and green?", "Lemon");
data.put("Which animal lives in water?", "Fish");
data.put("Which bird swims?", "Duck");
data.put("Which vehicle flies in the sky?", "Aeroplane");
data.put("What do we use to see time?", "Clock");
data.put("Which sense organ helps us feel?", "Skin");
data.put("Which insect carries food?", "Ant");
data.put("Which animal says meow?", "Cat");
data.put("Which animal says moo?", "Cow");
data.put("Which animal says neigh?", "Horse");
data.put("Which animal says roar?", "Lion");
data.put("Which animal says bark?", "Dog");
data.put("What shape is a ball?", "Circle");

// class 1 - 10 gk questions


data.put("What is the largest ocean in the world?", "Pacific Ocean");
data.put("Which is the longest river in the world?", "Nile River");
data.put("Who discovered India?", "Vasco da Gama");
data.put("Which is the smallest country in the world?", "Vatican City");
data.put("Which is the hottest planet in our solar system?", "Venus");
data.put("Which gas is needed for breathing?", "Oxygen");
data.put("Who is known as the father of computers?", "Charles Babbage");
data.put("Which country is the largest by area?", "Russia");
data.put("What is the national sport of India?", "Hockey");
data.put("Who was the first President of India?", "Dr. Rajendra Prasad");
data.put("Who built the Taj Mahal?", "Shah Jahan");
data.put("What is the capital of Australia?", "Canberra");
data.put("What is the capital of Canada?", "Ottawa");
data.put("How many states are there in India?", "28");
data.put("How many Union Territories are in India?", "8");
data.put("What is the square root of 144?", "12");
data.put("What is the chemical formula of salt?", "NaCl");
data.put("Which is the largest planet in the solar system?", "Jupiter");
data.put("Which is the closest planet to the sun?", "Mercury");
data.put("Who invented the telephone?", "Alexander Graham Bell");
data.put("Who discovered gravity?", "Isaac Newton");
data.put("Who invented electricity?", "Benjamin Franklin");
data.put("Which animal is known as the ship of the desert?", "Camel");
data.put("Which metal is the best conductor of electricity?", "Silver");
data.put("What is the national currency of Japan?", "Yen");
data.put("What is the national currency of China?", "Yuan");
data.put("What is the national currency of USA?", "Dollar");
data.put("What is the national bird of the USA?", "Bald Eagle");
data.put("Which is the national tree of India?", "Banyan Tree");
data.put("What is H2O commonly known as?", "Water");
data.put("What is the boiling point of water?", "100°C");
data.put("Which vitamin is known as the sunshine vitamin?", "Vitamin D");
data.put("Which vitamin is good for eyesight?", "Vitamin A");
data.put("Which is the longest bone in the human body?", "Femur");
data.put("Which organ pumps blood?", "Heart");
data.put("Which organ controls the body?", "Brain");
data.put("Which is the largest internal organ?", "Liver");
data.put("Which organ helps in breathing?", "Lungs");
data.put("Which gas do plants absorb from air?", "Carbon dioxide");
data.put("Which gas do plants release?", "Oxygen");
data.put("Who wrote the Ramayana?", "Valmiki");
data.put("Who wrote the Mahabharata?", "Vyasa");
data.put("Who wrote the national anthem of India?", "Rabindranath Tagore");
data.put("What is the national anthem of India?", "Jana Gana Mana");
data.put("What is the national song of India?", "Vande Mataram");
data.put("What is the capital of Russia?", "Moscow");
data.put("What is the capital of Germany?", "Berlin");
data.put("What is the capital of Italy?", "Rome");
data.put("Which animal has the longest neck?", "Giraffe");


data.put("Which is the longest wall in the world?", "The Great Wall of China");
data.put("Which country gifted the Statue of Liberty to the United States?", "France");
data.put("What is the largest desert in the world?", "Sahara Desert");
data.put("Which is the smallest ocean in the world?", "Arctic Ocean");
data.put("Which is the coldest place on Earth?", "Antarctica");
data.put("Which is the tallest mountain in the world?", "Mount Everest");
data.put("Which is the national river of India?", "Ganga");
data.put("Which is the largest island in the world?", "Greenland");
data.put("Who was the first Prime Minister of India?", "Jawaharlal Nehru");
data.put("Which state is known as the land of rising sun in India?", "Arunachal Pradesh");
data.put("What is the currency of the United Kingdom?", "Pound");
data.put("Which country is known as the land of maple leaf?", "Canada");
data.put("Which is the longest highway in India?", "NH-44");
data.put("Which is the tallest statue in the world?", "Statue of Unity");
data.put("Which is the national aquatic animal of India?", "Dolphin");
data.put("Which is the national heritage animal of India?", "Elephant");
data.put("Who was the first woman Prime Minister of India?", "Indira Gandhi");
data.put("Which city is known as the pink city of India?", "Jaipur");
data.put("Which city is known as the city of joy?", "Kolkata");
data.put("Which city is known as the city of pearls?", "Hyderabad");
data.put("Which city is known as the silicon valley of India?", "Bengaluru");
data.put("What is the largest organ of the human body?", "Skin");
data.put("Which is the heaviest metal?", "Osmium");
data.put("Which gas is used by plants to prepare food?", "Carbon dioxide");
data.put("What is the hardest substance in the human body?", "Tooth enamel");
data.put("What is the boiling point of water?", "100°C");
data.put("What is the freezing point of water?", "0°C");
data.put("Which blood cells fight diseases?", "White blood cells");
data.put("Which blood cells carry oxygen?", "Red blood cells");
data.put("What is the smallest unit of life?", "Cell");
data.put("What is the study of fossils called?", "Paleontology");
data.put("What is the study of stars called?", "Astronomy");
data.put("What is the study of weather called?", "Meteorology");
data.put("Who is known as the missile man of India?", "APJ Abdul Kalam");
data.put("What is the script used to write Hindi?", "Devanagari");
data.put("Which festival is known as the festival of lights?", "Diwali");
data.put("Which festival is known as the festival of colors?", "Holi");
data.put("Which festival marks the birth of Jesus Christ?", "Christmas");
data.put("Which is the longest railway platform in India?", "Gorakhpur");
data.put("Which is the national calendar of India?", "Saka Calendar");
data.put("What is the capital of Spain?", "Madrid");
data.put("What is the capital of South Korea?", "Seoul");
data.put("What is the capital of Brazil?", "Brasília");
data.put("What is the capital of South Africa?", "Pretoria");
data.put("What is the capital of Indonesia?", "Jakarta");
data.put("Which planet has rings around it?", "Saturn");
data.put("Which planet is known as the morning star?", "Venus");
data.put("Which is the largest gland in the human body?", "Liver");
data.put("How many players are there in a cricket team?", "11");
data.put("How many players are there in a football team?", "11");

data.put("Which animal is known as the ship of the desert?", "Camel");
data.put("Which animal is known as the king of the jungle?", "Lion");
data.put("Which animal has a hump?", "Camel");
data.put("Which bird lays the largest eggs?", "Ostrich");
data.put("Which bird is called the king of birds?", "Eagle");
data.put("Which insect makes honey?", "Bee");
data.put("Which insect has 100 legs?", "Centipede");
data.put("Which animal can live both on land and in water?", "Frog");
data.put("Which animal changes its color?", "Chameleon");
data.put("Which fish is the fastest?", "Sailfish");
data.put("Which is the largest mammal?", "Blue Whale");
data.put("Which is the smallest bird?", "Bee Hummingbird");
data.put("Which planet is closest to Earth?", "Venus");
data.put("Which planet is farthest from the Sun?", "Neptune");
data.put("Which planet is the brightest?", "Venus");
data.put("Which is the hottest place on Earth?", "Death Valley");
data.put("Which is the coldest planet?", "Neptune");
data.put("Which is the smallest state in India by area?", "Goa");
data.put("Which is the largest state in India by population?", "Uttar Pradesh");
data.put("Which river flows longest in India?", "Ganga");
data.put("Which is the oldest mountain range in India?", "Aravalli Range");
data.put("Which is the longest lake in India?", "Vembanad Lake");
data.put("Which is the tallest waterfall in India?", "Kunchikal Falls");
data.put("Which is the longest dam in India?", "Hirakud Dam");
data.put("Which is the national tree of India?", "Banyan Tree");
data.put("Which is the national fruit of India?", "Mango");
data.put("Which is the national bird of India?", "Peacock");
data.put("Which is the national animal of India?", "Tiger");
data.put("Which is the national flower of India?", "Lotus");
data.put("Which is the national emblem of India?", "Lion Capital of Ashoka");
data.put("Which is the national currency of India?", "Rupee");
data.put("What is the main festival of Sikhs?", "Guru Nanak Jayanti");
data.put("What is the main festival of Muslims?", "Eid");
data.put("What is the main festival of Christians?", "Christmas");
data.put("What is the festival of harvest in Punjab?", "Baisakhi");
data.put("Which festival celebrates the victory of good over evil?", "Dussehra");
data.put("Which festival celebrates the bond between brothers and sisters?", "Raksha Bandhan");
data.put("Which festival marks the Hindu New Year?", "Ugadi");
data.put("Which festival is celebrated with kites?", "Makar Sankranti");
data.put("Which is the main language of Tamil Nadu?", "Tamil");
data.put("Which is the main language of Maharashtra?", "Marathi");
data.put("Which is the main language of West Bengal?", "Bengali");
data.put("Which is the main language of Punjab?", "Punjabi");
data.put("Which is the main language of Kerala?", "Malayalam");
data.put("Which is the main language of Odisha?", "Odia");
data.put("What is the capital of Gujarat?", "Gandhinagar");
data.put("What is the capital of Punjab?", "Chandigarh");
data.put("What is the capital of Rajasthan?", "Jaipur");
data.put("What is the capital of Odisha?", "Bhubaneswar");
data.put("What is the capital of Bihar?", "Patna");

data.put("What is the capital of Haryana?", "Chandigarh");
data.put("What is the capital of Madhya Pradesh?", "Bhopal");
data.put("What is the capital of Jharkhand?", "Ranchi");
data.put("What is the capital of Chhattisgarh?", "Raipur");
data.put("What is the capital of Uttarakhand?", "Dehradun");
data.put("What is the capital of Telangana?", "Hyderabad");
data.put("What is the capital of Jammu and Kashmir?", "Srinagar and Jammu");
data.put("Which state is called the land of five rivers?", "Punjab");
data.put("Which state is known as God's own country?", "Kerala");
data.put("Which state is known as the spice garden of India?", "Kerala");
data.put("Which state is known as the fruit bowl of India?", "Himachal Pradesh");
data.put("Which state is known as the land of dawn-lit mountains?", "Arunachal Pradesh");
data.put("Which state is known as the land of festivals?", "Nagaland");
data.put("Which state is known as the land of kings?", "Rajasthan");
data.put("Which state is known for tea gardens?", "Assam");
data.put("Which state is famous for the Sun Temple?", "Odisha");
data.put("Which state is famous for Gir National Park?", "Gujarat");
data.put("Which state is famous for Kaziranga National Park?", "Assam");
data.put("Which river is the longest in the world?", "Nile");
data.put("Which river flows through Egypt?", "Nile");
data.put("Which is the largest country in the world by area?", "Russia");
data.put("Which is the smallest country in the world?", "Vatican City");
data.put("Which country is known as the land of the rising sun?", "Japan");
data.put("Which country is known as the land of the midnight sun?", "Norway");
data.put("Which country is known as the land of white elephants?", "Thailand");
data.put("Which country invented paper?", "China");
data.put("Which country invented gunpowder?", "China");
data.put("Which country gifted the Statue of Liberty to the USA?", "France");
data.put("Which country is known for the Great Barrier Reef?", "Australia");
data.put("Which is the longest river in South India?", "Godavari");
data.put("Which is the largest delta in the world?", "Sundarbans Delta");
data.put("Which is the deepest ocean?", "Pacific Ocean");
data.put("Which is the hottest planet in the solar system?", "Venus");
data.put("Which is the coldest place on Earth?", "Antarctica");
data.put("Which metal is liquid at room temperature?", "Mercury");
data.put("What is H2O?", "Water");
data.put("What is CO2?", "Carbon dioxide");
data.put("What is the largest bone in the human body?", "Femur");
data.put("What is the smallest bone in the human body?", "Stapes");
data.put("How many bones are in the human body?", "206");
data.put("How many teeth does an adult human have?", "32");
data.put("What is the full form of CPU?", "Central Processing Unit");
data.put("What is the full form of USB?", "Universal Serial Bus");
data.put("What is the full form of WWW?", "World Wide Web");
data.put("Which device is used to measure temperature?", "Thermometer");
data.put("Which device is used to measure earthquakes?", "Seismograph");
data.put("Which device is used to measure atmospheric pressure?", "Barometer");
data.put("What is the largest man-made structure in the world?", "The Great Wall of China");
data.put("Which ocean is on the west of India?", "Arabian Sea");
data.put("Which ocean is on the east of India?", "Bay of Bengal");


// UPSC LEVEL QUESTIONS STARTING

data.put("Who is known as the Father of the Indian Constitution?", "Dr. B. R. Ambedkar");
data.put("Which article deals with the Right to Equality?", "Article 14");
data.put("Which article deals with the Right to Freedom?", "Article 19");
data.put("Which article deals with the Right to Life?", "Article 21");
data.put("Which amendment lowered the voting age to 18?", "61st Amendment");
data.put("When was the Indian Constitution adopted?", "26 November 1949");
data.put("When did the Indian Constitution come into force?", "26 January 1950");
data.put("Who was the first President of India?", "Dr. Rajendra Prasad");
data.put("Who was the first Prime Minister of India?", "Jawaharlal Nehru");
data.put("Who was the first Vice President of India?", "Dr. S. Radhakrishnan");
data.put("Who was the first Chief Justice of India?", "H. J. Kania");
data.put("Who was the first Governor-General of independent India?", "Lord Mountbatten");
data.put("Who was the first Indian Governor-General?", "C. Rajagopalachari");
data.put("Which article deals with emergency provisions?", "Article 352, 356, 360");
data.put("Which article deals with the abolition of untouchability?", "Article 17");
data.put("Which schedule contains the official languages of India?", "8th Schedule");
data.put("Which schedule deals with Panchayati Raj?", "11th Schedule");
data.put("Which schedule deals with municipalities?", "12th Schedule");
data.put("Which is the largest river in India?", "Ganga");
data.put("Which is the longest river in the world?", "Nile");
data.put("Which is the largest desert in the world?", "Sahara Desert");
data.put("Which is the largest continent in the world?", "Asia");
data.put("Which is the smallest continent in the world?", "Australia");
data.put("Which is the largest ocean in the world?", "Pacific Ocean");
data.put("Which is the smallest ocean in the world?", "Arctic Ocean");
data.put("Which is the highest peak in the world?", "Mount Everest");
data.put("Which is the highest peak in India?", "Kanchenjunga");
data.put("Which river is known as Dakshin Ganga?", "Godavari");
data.put("Which river is known as the Sorrow of Bihar?", "Kosi");
data.put("Which river is known as the Sorrow of Bengal?", "Damodar");
data.put("Which state has the highest literacy rate?", "Kerala");
data.put("Which state has the lowest literacy rate?", "Bihar");
data.put("Which state has the largest area in India?", "Rajasthan");
data.put("Which state has the smallest area in India?", "Goa");
data.put("Which state has the highest population in India?", "Uttar Pradesh");
data.put("Which state has the longest coastline?", "Gujarat");
data.put("Which is the longest highway in India?", "NH-44");
data.put("Which is the longest railway platform in India?", "Gorakhpur");
data.put("Which is the longest dam in India?", "Hirakud Dam");
data.put("Which is the highest dam in India?", "Tehri Dam");
data.put("Which is the largest lake in India?", "Vembanad Lake");
data.put("Which is the largest freshwater lake in the world?", "Lake Superior");
data.put("Which is the deepest lake in the world?", "Lake Baikal");
data.put("Which is the largest island in the world?", "Greenland");
data.put("Which is the highest waterfall in India?", "Kunchikal Falls");
data.put("Which is the largest delta in the world?", "Sundarbans Delta");
data.put("Which is the longest glacier in India?", "Siachen Glacier");
data.put("Who introduced railways in India?", "Lord Dalhousie");
data.put("Who introduced the postal system in India?", "Lord Dalhousie");

data.put("Which is the longest river in India by length within India?", "Ganga");
data.put("Which is the largest desert in India?", "Thar Desert");
data.put("Which is the oldest mountain range in India?", "Aravalli Range");
data.put("Which is the youngest mountain range in the world?", "Himalayas");
data.put("Which is the largest plateau in India?", "Deccan Plateau");
data.put("Which is the highest gateway in India?", "Buland Darwaza");
data.put("Where is the Sun Temple located?", "Konark");
data.put("Where is the Brihadeeswara Temple located?", "Thanjavur");
data.put("Where is the Golden Temple located?", "Amritsar");
data.put("Where is the Jagannath Temple located?", "Puri");
data.put("Who founded the Maurya Empire?", "Chandragupta Maurya");
data.put("Who was the most famous Mauryan ruler?", "Ashoka");
data.put("Who founded the Gupta Empire?", "Sri Gupta");
data.put("Who is known as the Napoleon of India?", "Samudragupta");
data.put("Who was the founder of the Mughal Empire?", "Babur");
data.put("Who was the greatest Mughal emperor?", "Akbar");
data.put("Who built the Taj Mahal?", "Shah Jahan");
data.put("Who built the Red Fort?", "Shah Jahan");
data.put("Who built the Qutub Minar?", "Qutb-ud-din Aibak");
data.put("Who built the Charminar?", "Muhammad Quli Qutb Shah");
data.put("Who was the first Mughal emperor?", "Babur");
data.put("Who was the last Mughal emperor?", "Bahadur Shah Zafar");
data.put("Who introduced the Mansabdari system?", "Akbar");
data.put("Who introduced the Permanent Settlement?", "Lord Cornwallis");
data.put("Who introduced the Ryotwari System?", "Thomas Munro");
data.put("Who introduced the Mahalwari System?", "Holt Mackenzie");
data.put("Which movement started after the Partition of Bengal?", "Swadeshi Movement");
data.put("When was Bengal partitioned?", "1905");
data.put("Who started the Civil Disobedience Movement?", "Mahatma Gandhi");
data.put("When did the Quit India Movement start?", "1942");
data.put("When did the Non-Cooperation Movement start?", "1920");
data.put("Who founded the Indian National Army?", "Subhas Chandra Bose");
data.put("Who founded the Indian National Congress?", "A. O. Hume");
data.put("When was the Indian National Congress founded?", "1885");
data.put("Who was the first woman President of the Indian National Congress?", "Annie Besant");
data.put("Who was the first Indian woman President of the Indian National Congress?", "Sarojini Naidu");
data.put("Who gave the slogan Jai Hind?", "Subhas Chandra Bose");
data.put("Who gave the slogan Do or Die?", "Mahatma Gandhi");
data.put("Who gave the slogan Inquilab Zindabad?", "Bhagat Singh");
data.put("Who wrote the book Discovery of India?", "Jawaharlal Nehru");
data.put("Who wrote India Wins Freedom?", "Maulana Abul Kalam Azad");
data.put("Who wrote Arthashastra?", "Chanakya");
data.put("Who wrote Indica?", "Megasthenes");
data.put("Who wrote the National Anthem of India?", "Rabindranath Tagore");
data.put("Who wrote the National Song of India?", "Bankim Chandra Chatterjee");
data.put("Which is the highest civilian award in India?", "Bharat Ratna");
data.put("Which is the highest military award in India?", "Param Vir Chakra");
data.put("Which Indian state has the maximum forest area?", "Madhya Pradesh");
data.put("Which Indian state is the largest producer of rice?", "West Bengal");
data.put("Which Indian state is the largest producer of wheat?", "Uttar Pradesh");

data.put("Which Indian state is the largest producer of milk?", "Uttar Pradesh");
data.put("Which Indian state is the largest producer of sugarcane?", "Uttar Pradesh");
data.put("Which Indian state is the largest producer of cotton?", "Gujarat");
data.put("Which Indian state is the largest producer of tea?", "Assam");
data.put("Which Indian state is the largest producer of coffee?", "Karnataka");
data.put("Which Indian state is the largest producer of spices?", "Kerala");
data.put("Which Indian state is the largest producer of tobacco?", "Andhra Pradesh");
data.put("Which Indian state is the largest producer of jute?", "West Bengal");
data.put("Which Indian state is the largest producer of coal?", "Jharkhand");
data.put("Which Indian state is the largest producer of iron ore?", "Odisha");
data.put("Which Indian state has the highest number of airports?", "Uttar Pradesh");
data.put("Which Indian state has the highest number of districts?", "Uttar Pradesh");
data.put("Which is the oldest stock exchange in India?", "Bombay Stock Exchange");
data.put("Which is the largest public sector bank in India?", "State Bank of India");
data.put("Who issues currency in India?", "Reserve Bank of India");
data.put("Which body regulates the share market in India?", "SEBI");
data.put("Which tax was replaced by GST?", "VAT and Service Tax");
data.put("When was GST introduced in India?", "2017");
data.put("What is the national sport of India?", "Hockey (Unofficial)");
data.put("Which is the largest stadium in India?", "Narendra Modi Stadium");
data.put("Which is the largest stadium in the world?", "Narendra Modi Stadium");
data.put("Which is the oldest mountain range in the world?", "Aravalli Range");
data.put("Which is the fastest land animal?", "Cheetah");
data.put("Which is the largest animal in the world?", "Blue Whale");
data.put("Which is the tallest animal?", "Giraffe");
data.put("Which animal is known as the ship of the desert?", "Camel");
data.put("Which gas is essential for photosynthesis?", "Carbon dioxide");
data.put("Which gas is essential for respiration?", "Oxygen");
data.put("Which gas is known as laughing gas?", "Nitrous oxide");
data.put("Which gas is known as cooking gas?", "LPG");
data.put("Which element is the lightest?", "Hydrogen");
data.put("Which element is the heaviest naturally occurring?", "Uranium");
data.put("Which metal is the most reactive?", "Potassium");
data.put("Which metal is liquid at room temperature?", "Mercury");
data.put("What is the chemical name of common salt?", "Sodium Chloride");
data.put("What is the chemical formula of water?", "H2O");
data.put("What is the chemical formula of carbon dioxide?", "CO2");
data.put("What is the SI unit of force?", "Newton");
data.put("What is the SI unit of energy?", "Joule");
data.put("What is the SI unit of power?", "Watt");
data.put("What is the SI unit of electric current?", "Ampere");
data.put("What is the SI unit of temperature?", "Kelvin");
data.put("Which organ purifies blood?", "Kidney");
data.put("Which organ pumps blood?", "Heart");
data.put("Which organ controls the body?", "Brain");
data.put("Which organ helps in breathing?", "Lungs");
data.put("Which is the largest gland in the human body?", "Liver");
data.put("Which is the longest bone in the human body?", "Femur");
data.put("Which is the smallest bone in the human body?", "Stapes");
data.put("How many bones are in the human body?", "206");



data.put("Which vitamin is produced in the skin by sunlight?", "Vitamin D");
data.put("Which vitamin is known as ascorbic acid?", "Vitamin C");
data.put("Which vitamin is responsible for blood clotting?", "Vitamin K");
data.put("Which vitamin is good for eyesight?", "Vitamin A");
data.put("Which blood group is known as the universal donor?", "O Negative");
data.put("Which blood group is known as the universal recipient?", "AB Positive");
data.put("Which disease is caused by deficiency of iodine?", "Goitre");
data.put("Which disease is caused by deficiency of vitamin D?", "Rickets");
data.put("Which disease is caused by deficiency of iron?", "Anaemia");
data.put("Which disease is spread by female Anopheles mosquito?", "Malaria");
data.put("Which disease is caused by a virus?", "Influenza");
data.put("Which disease is caused by bacteria?", "Tuberculosis");
data.put("Which organ produces insulin?", "Pancreas");
data.put("Which organ stores bile?", "Gallbladder");
data.put("Which organ purifies blood in the human body?", "Kidney");
data.put("Which organ is called the powerhouse of the cell?", "Mitochondria");
data.put("Which organ is called the control center of the body?", "Brain");
data.put("Which is the highest civillian award in India?", "Bharat Ratna");
data.put("Which is the second-highest civilian award in India?", "Padma Vibhushan");
data.put("Which is the highest gallantry award in India?", "Param Vir Chakra");
data.put("Which is the highest peacetime gallantry award in India?", "Ashoka Chakra");
data.put("Who was the first woman recipient of the Bharat Ratna?", "Indira Gandhi");
data.put("Who was the first posthumous recipient of Bharat Ratna?", "Lal Bahadur Shastri");
data.put("Who was the first recipient of Bharat Ratna?", "C. Rajagopalachari, Dr. S. Radhakrishnan, C. V. Raman");
data.put("Who was the first Indian to win Nobel Prize?", "Rabindranath Tagore");
data.put("Who was the first Indian woman to win Nobel Prize?", "Mother Teresa");
data.put("Who won India's first Olympic medal?", "Norman Pritchard");
data.put("Who won India's first individual Olympic gold medal?", "Abhinav Bindra");
data.put("Which country is the largest producer of wheat?", "China");
data.put("Which country is the largest producer of rice?", "China");
data.put("Which country is the largest producer of milk?", "India");
data.put("Which country is the largest producer of coffee?", "Brazil");
data.put("Which country is the largest producer of sugarcane?", "Brazil");
data.put("Which country is the largest producer of tea?", "China");
data.put("Which country is the largest producer of gold?", "China");
data.put("Which country is the largest producer of crude oil?", "United States");
data.put("Which country is the largest exporter of crude oil?", "Saudi Arabia");
data.put("Which country has the largest population in the world?", "India");
data.put("Which country has the largest area in the world?", "Russia");
data.put("Which country has the smallest population?", "Vatican City");
data.put("Which is the oldest democracy in the world?", "Greece");
data.put("Which is the largest democracy in the world?", "India");
data.put("Who is the Supreme Commander of the Armed Forces in India?", "President of India");
data.put("Who appoints the Prime Minister of India?", "President of India");
data.put("Who appoints the Chief Justice of India?", "President of India");
data.put("Who appoints the Governor of a State?", "President of India");
data.put("Who administers oath to the President of India?", "Chief Justice of India");
data.put("Who administers oath to the Prime Minister of India?", "President of India");
data.put("Who administers oath to the Governor?", "Chief Justice of High Court");


data.put("Who administers oath to the Chief Justice of India?", "President of India");
data.put("Who administers oath to the Chief Minister?", "Governor");
data.put("Who is known as the father of the Indian Space Program?", "Vikram Sarabhai");
data.put("Who is known as the missile man of India?", "APJ Abdul Kalam");
data.put("Where is ISRO headquarters located?", "Bengaluru");
data.put("Where is DRDO headquarters located?", "New Delhi");
data.put("Where is BARC located?", "Mumbai");
data.put("Where is India's nuclear test site located?", "Pokhran");
data.put("In which year did India conduct its first nuclear test?", "1974");
data.put("What was the name of India's first nuclear test?", "Smiling Buddha");
data.put("In which year did India conduct Operation Shakti?", "1998");
data.put("Which was India's first satellite?", "Aryabhata");
data.put("Which was India's first mission to the Moon?", "Chandrayaan-1");
data.put("Which was India's first mission to Mars?", "Mangalyaan");
data.put("Which is India's heaviest satellite?", "GSAT-11");
data.put("Which Indian satellite discovered water on the Moon?", "Chandrayaan-1");
data.put("Which planet is known as the Red Planet?", "Mars");
data.put("Which planet is known as the Blue Planet?", "Earth");
data.put("Which planet is known as the Morning Star?", "Venus");
data.put("Which planet has the most moons?", "Jupiter");
data.put("Which is the largest planet in the solar system?", "Jupiter");
data.put("Which is the smallest planet in the solar system?", "Mercury");
data.put("Which is the hottest planet in the solar system?", "Venus");
data.put("Which is the coldest planet in the solar system?", "Neptune");
data.put("What is the speed of light?", "3 × 10^8 m/s");
data.put("What is the unit of electric current?", "Ampere");
data.put("What is the unit of power?", "Watt");
data.put("What is the unit of pressure?", "Pascal");
data.put("What is the unit of frequency?", "Hertz");
data.put("What is the SI unit of energy?", "Joule");
data.put("Which law states that every action has an equal and opposite reaction?", "Newton's Third Law");
data.put("Which gas forms the highest percentage in the atmosphere?", "Nitrogen");
data.put("Which gas is used in balloons?", "Helium");
data.put("Which gas is used for breathing by divers?", "Oxygen");
data.put("Which metal is the best conductor of electricity?", "Silver");
data.put("Which metal is used in thermometers?", "Mercury");
data.put("Which chemical is known as quicklime?", "Calcium oxide");
data.put("Which chemical is known as slaked lime?", "Calcium hydroxide");
data.put("Which chemical is known as bleaching powder?", "Calcium hypochlorite");
data.put("Which wave is used for communication?", "Radio waves");
data.put("Which wave is used in microwaves?", "Microwave radiation");
data.put("Which organ is affected by jaundice?", "Liver");
data.put("Which organ is affected by pneumonia?", "Lungs");
data.put("Which organ is affected by bronchitis?", "Lungs");
data.put("Which organ is affected by hepatitis?", "Liver");
data.put("Which organ is affected by nephritis?", "Kidney");
data.put("Which vitamin deficiency causes night blindness?", "Vitamin A");
data.put("Which vitamin deficiency causes scurvy?", "Vitamin C");
data.put("Which vitamin deficiency causes rickets?", "Vitamin D");
data.put("Which vitamin deficiency causes beriberi?", "Vitamin B1");


data.put("What is the tenure of the President of India?", "5 years");
data.put("What is the tenure of the Prime Minister of India?", "No fixed term");
data.put("What is the tenure of the Governor?", "5 years");
data.put("Who can remove the Governor of a state?", "President of India");
data.put("Who can dissolve the Lok Sabha?", "President of India");
data.put("What is the minimum age for Lok Sabha membership?", "25 years");
data.put("What is the minimum age for Rajya Sabha membership?", "30 years");
data.put("What is the minimum age for voting in India?", "18 years");
data.put("What is the minimum age to become the President of India?", "35 years");
data.put("What is the minimum age to become the Vice President?", "35 years");
data.put("Which article deals with President's Rule?", "Article 356");
data.put("Which article deals with Financial Emergency?", "Article 360");
data.put("Which article deals with National Emergency?", "Article 352");
data.put("Which article defines citizenship?", "Article 5 to 11");
data.put("Which article establishes the Supreme Court?", "Article 124");
data.put("Which article establishes the High Courts?", "Article 214");
data.put("Which article gives special status to Jammu & Kashmir (now removed)?", "Article 370");
data.put("When was Article 370 abrogated?", "2019");
data.put("Which amendment abolished the Privy Purses?", "26th Amendment");
data.put("Which amendment made Right to Education a fundamental right?", "86th Amendment");
data.put("Which article deals with the Right to Education?", "Article 21A");
data.put("Which article deals with the Right against Exploitation?", "Article 23");
data.put("Which article deals with the Right to Religion?", "Article 25");
data.put("Which article deals with Cultural and Educational Rights?", "Article 29");
data.put("Which article deals with the Right to Constitutional Remedies?", "Article 32");
data.put("What is the guardian of the Constitution?", "Supreme Court");
data.put("Which body conducts elections in India?", "Election Commission");
data.put("Who is the ex-officio Chairman of Rajya Sabha?", "Vice President of India");
data.put("Who presides over Lok Sabha?", "Speaker");
data.put("What is the total strength of Lok Sabha?", "552");
data.put("What is the total strength of Rajya Sabha?", "250");
data.put("Which state has the maximum Lok Sabha seats?", "Uttar Pradesh");
data.put("Which state has the maximum Rajya Sabha seats?", "Uttar Pradesh");
data.put("Which was the first state formed on linguistic basis?", "Andhra Pradesh");
data.put("In which year was Andhra Pradesh formed?", "1953");
data.put("Which is the largest biosphere reserve in India?", "Gulf of Mannar");
data.put("Which is the largest national park in India?", "Hemis National Park");
data.put("Which is the first national park in India?", "Jim Corbett National Park");
data.put("Which animal is the national animal of India?", "Tiger");
data.put("Which bird is the national bird of India?", "Peacock");
data.put("Which flower is the national flower of India?", "Lotus");
data.put("Which fruit is the national fruit of India?", "Mango");
data.put("Which tree is the national tree of India?", "Banyan Tree");
data.put("Which river is the national river of India?", "Ganga");
data.put("Which aquatic animal is the national aquatic animal of India?", "Dolphin");
data.put("Which sport is the national sport of India?", "Hockey (Unofficial)");
data.put("Which is the national emblem of India?", "Lion Capital of Ashoka");
data.put("What is the motto of the national emblem?", "Satyameva Jayate");
data.put("Who gave the slogan Satyameva Jayate?", "Mundaka Upanishad");
data.put("Which is the largest temple complex in India?", "Rameswaram Temple");
data.put("Which language has the highest number of speakers in India?", "Hindi");
data.put("Which language is the oldest in India?", "Tamil");
data.put("Which is the highest civilian award in India?", "Bharat Ratna");
data.put("Which is the highest civilian award in the world?", "Nobel Prize");
data.put("Which Indian state has the largest coastline?", "Gujarat");
data.put("Which Indian state has the smallest coastline?", "Goa");
data.put("Which country has the longest coastline in the world?", "Canada");
data.put("Which country has the highest GDP?", "United States");
data.put("Which country has the fastest growing economy?", "India");



// CURRENT AFFIARS

data.put("Which country hosted the G20 Summit 2023?", "India");
data.put("Who is the current President of India?", "Droupadi Murmu");
data.put("Who is the current Prime Minister of India?", "Narendra Modi");
data.put("Which country won the ICC Cricket World Cup 2023?", "Australia");
data.put("Which country launched Chandrayaan 3?", "India");
data.put("Which mission landed near the Moon's south pole?", "Chandrayaan-3");
data.put("Which country won the FIFA World Cup 2022?", "Argentina");
data.put("Who won the Nobel Peace Prize 2023?", "Narges Mohammadi");
data.put("Which company became the first 3 trillion dollar company?", "Apple");
data.put("Which country launched the digital rupee?", "India");
data.put("Which bank introduced the e-Rupee?", "Reserve Bank of India");
data.put("Which country launched 6G experiments in 2023?", "China");
data.put("Which city hosted the G7 Summit 2023?", "Hiroshima");
data.put("Which country became the 31st member of NATO?", "Finland");
data.put("Which Indian airport won best airport award 2023?", "Delhi IGI Airport");
data.put("Which company launched the Starship rocket?", "SpaceX");
data.put("Who is the CEO of Twitter (X)?", "Elon Musk");
data.put("Which state launched the Gruha Lakshmi Scheme?", "Karnataka");
data.put("Which state launched Lakshmir Bhandar Scheme?", "West Bengal");
data.put("Which country hosted the FIFA World Cup 2022?", "Qatar");
data.put("Who is the Chief Justice of India?", "D. Y. Chandrachud");
data.put("Which country passed the world's first AI law?", "European Union");
data.put("Which state launched the Smart Township Scheme?", "Andhra Pradesh");
data.put("Which Indian city hosted the SCO Summit 2023?", "New Delhi");
data.put("Which is India's first solar mission?", "Aditya-L1");
data.put("Who is the current President of the United States?", "Joe Biden");
data.put("Which country has the world’s highest GDP?", "United States");
data.put("Which country has the largest population in 2023?", "India");
data.put("Which country discovered water on the Moon first?", "India (Chandrayaan-1)");
data.put("Which Indian city is proposed to host Olympics 2036?", "Ahmedabad");
data.put("Who is the CEO of Google?", "Sundar Pichai");
data.put("Who is the CEO of Microsoft?", "Satya Nadella");
data.put("Which country banned TikTok first?", "India");
data.put("Which country launched the Artemis Moon Mission?", "USA");
data.put("Which state won cleanest state award 2023?", "Madhya Pradesh");
data.put("Which country won the Asia Cup 2023?", "India");
data.put("Which country won the Under-19 World Cup 2024?", "India");
data.put("Which company bought Twitter?", "Elon Musk");
data.put("Which Indian state has the highest literacy rate?", "Kerala");
data.put("Which Indian state has the lowest literacy rate?", "Bihar");
data.put("Which country won the T20 World Cup 2022?", "England");
data.put("What is India's first bullet train project?", "Mumbai–Ahmedabad");
data.put("Which country hosts the World Economic Forum?", "Switzerland");
data.put("Which country won the Asia Cup 2022?", "Sri Lanka");
data.put("Which state launched Mission Shakti?", "Odisha");
data.put("Which country won the Hockey World Cup 2023?", "Germany");
data.put("Who is the chairman of ISRO?", "S. Somanath");
data.put("Which country launched the JUICE mission?", "European Space Agency");
data.put("Which country produces the most gold?", "China");
data.put("Which Indian city has the world’s largest stadium?", "Ahmedabad");



data.put("Which state has the highest forest cover in India?", "Madhya Pradesh");
data.put("Which country topped the World Happiness Index 2023?", "Finland");
data.put("Which country ranked lowest in the World Happiness Index 2023?", "Afghanistan");
data.put("Which state topped the Ease of Doing Business 2023?", "Andhra Pradesh");
data.put("Which country won Miss Universe 2023?", "Nicaragua");
data.put("Which Indian company became the first 200 billion dollar company?", "Reliance Industries");
data.put("Which state launched Gruha Jyothi Scheme?", "Karnataka");
data.put("Which state launched Ladli Behna Yojana?", "Madhya Pradesh");
data.put("Who won Ballon d'Or 2023?", "Lionel Messi");
data.put("Who is the richest person in the world 2023?", "Elon Musk");
data.put("Who is the richest woman in the world 2023?", "Françoise Bettencourt Meyers");
data.put("Which country opened the world's first AI school?", "UAE");
data.put("Which airport won Cleanest Airport India 2023?", "Delhi IGI Airport");
data.put("Which country topped the Global Gender Gap Index 2023?", "Iceland");
data.put("What is India's rank in Gender Gap Index 2023?", "127");
data.put("Which state launched the Kisan Rin Portal?", "Odisha");
data.put("Which country announced room-temperature superconductor LK-99?", "South Korea");
data.put("Who became new CBDT chairman 2023?", "Nitin Gupta");
data.put("Which state is top in solar power production?", "Rajasthan");
data.put("Which state is top in wind energy production?", "Tamil Nadu");
data.put("Which country hosted the Asian Games 2023?", "China");
data.put("Who won Badminton gold for India in Asian Games 2023?", "Satwiksairaj Rankireddy and Chirag Shetty");
data.put("Which state launched Amma Vodi Scheme?", "Andhra Pradesh");
data.put("Which state launched Haritha Haram Programme?", "Telangana");
data.put("Where was Men's Hockey World Cup 2023 held?", "Odisha");
data.put("Which country launched Ispace Moon Mission 2023?", "Japan");
data.put("Who is the RBI Governor 2023?", "Shaktikanta Das");
data.put("Which country launched F-21 fighter jet with India?", "USA");
data.put("Which state launched Pink Auto Scheme?", "Tamil Nadu");
data.put("Where is India's first hydrogen train planned?", "Haryana");
data.put("Who won Oscars 2023 Best Actor?", "Brendan Fraser");
data.put("Who won Oscars 2023 Best Actress?", "Michelle Yeoh");
data.put("Which Indian song won Oscar 2023?", "Naatu Naatu");
data.put("Which movie won Oscar 2023 Best Picture?", "Everything Everywhere All at Once");
data.put("Which Indian state started Annapurna Scheme?", "Rajasthan");
data.put("Which Indian city will host Metaverse Startup Conclave 2023?", "Gujarat");
data.put("Which Indian metro became the first 100% renewable-powered metro?", "Delhi Metro");
data.put("Which country launched the first 3D printed rocket?", "USA");
data.put("Which is India's first vertical lift railway bridge?", "Pamban Bridge 2.0");
data.put("Which is the highest railway bridge in India?", "Chenab Bridge");
data.put("Where is the world's highest railway bridge located?", "Jammu and Kashmir");
data.put("Which state launched APY Pension Scheme Expansion?", "Maharashtra");
data.put("Which country launched the Triton X climate satellite?", "China");
data.put("Which company introduced the M3 chip?", "Apple");
data.put("Which company launched the Planet IX satellite?", "SpaceX");
data.put("Which state got Amaravati as its capital again?", "Andhra Pradesh");
data.put("Which state launched the Kalamritam Project?", "Kerala");
data.put("Where was APEC Summit 2023 held?", "San Francisco");
data.put("Which country launched the Long March reusable rocket?", "China");
data.put("Which Indian state first implemented Right to Health Act?", "Rajasthan");



data.put("Which country launched the Temis Climate Mission?", "Japan");
data.put("Which state approved Caste Census 2023?", "Bihar");
data.put("Which city hosted the Women’s World Boxing Championship 2023?", "New Delhi");
data.put("Which Indian athlete won Javelin Gold at World Athletics 2023?", "Neeraj Chopra");
data.put("Which state launched Ladli Laxmi Scheme?", "Madhya Pradesh");
data.put("Which state is the highest fruit producer in India?", "Uttar Pradesh");
data.put("Which state is the highest vegetable producer in India?", "Uttar Pradesh");
data.put("Which state is the highest sugarcane producer?", "Uttar Pradesh");
data.put("Which state launched Free Laptop Scheme 2023?", "Uttar Pradesh");
data.put("Which country announced Digital Avatar Passport?", "Finland");
data.put("Which company launched the world’s fastest charging battery?", "CATL (China)");
data.put("Which country launched the world’s first wooden satellite?", "Japan");
data.put("Which state started Free Bus Travel for Women?", "Tamil Nadu");
data.put("Who won the Nobel Prize in Physics 2023?", "Agostini, Krausz, L'Huillier");
data.put("Who won the Nobel Prize in Chemistry 2023?", "Bawendi, Brus, Ekimov");
data.put("Who won the Nobel Prize in Medicine 2023?", "Karikó and Weissman");
data.put("Which company launched the Optimus Humanoid Robot?", "Tesla");
data.put("Which country banned single-use plastic nationwide in 2023?", "India");
data.put("Which state launched the Annapurna Food Scheme?", "Rajasthan");
data.put("Which state hosted Startup Conclave 2023?", "Gujarat");
data.put("Which metro became India's first with 100% renewable energy?", "Delhi Metro");
data.put("Which country launched the first 3D-printed rocket?", "USA");
data.put("Where is India’s highest railway bridge located?", "Jammu and Kashmir");
data.put("Which is India's first vertical lift railway bridge?", "Pamban Bridge 2.0");
data.put("Which country launched the Triton X Climate Satellite?", "China");
data.put("Which company released the M3 chip?", "Apple");
data.put("Which company launched the Planet IX satellite?", "SpaceX");
data.put("Which state restored Amaravati as capital in 2023?", "Andhra Pradesh");
data.put("Which state launched Kalamritam Project?", "Kerala");
data.put("Where was APEC Summit 2023 held?", "San Francisco");
data.put("Which country tested reusable Long March Rocket?", "China");
data.put("Which state implemented Right to Health Act first?", "Rajasthan");
data.put("What is India's ranking in Global Hunger Index 2023?", "111");
data.put("Which Indian city hosted G20 Summit 2023?", "New Delhi");
data.put("Who won Women's Football World Cup 2023?", "Spain");
data.put("Which tech company launched GPT-4?", "OpenAI");
data.put("Which country launched world’s first 7G tests?", "South Korea");
data.put("Which country launched the world’s first AI university?", "UAE");
data.put("Which city topped Swachh Survekshan 2023?", "Indore");
data.put("Which country won the Asian Hockey Champions Trophy 2023?", "India");
data.put("Which country won the 2023 ODI Asia Cup?", "India");
data.put("Which country won Asia Cup 2024 (U19)?", "India");
data.put("Which Indian state launched Mukhyamantri Ladli Behna Yojana?", "Madhya Pradesh");
data.put("Who won the ICC Cricketer of the Year 2023?", "Virat Kohli");
data.put("Who won the ICC Emerging Player of the Year 2023?", "Yashasvi Jaiswal");
data.put("Which country launched the world’s first AI-based exam system?", "China");
data.put("Where is India’s first Vande Bharat sleeper train being built?", "Chennai");
data.put("Which Indian city got world’s largest solar rooftop plant?", "Surat");
data.put("Which state launched the Jagananna Vidya Deevena Scheme?", "Andhra Pradesh");
data.put("Which country launched reusable spaceplane ‘Shenzhou’?", "China");
data.put("Which Indian startup became a unicorn in 2023?", "InCred Finance");


// HISTORY

data.put("Who was the first Emperor of the Maurya Empire?", "Chandragupta Maurya");
data.put("Who was the most famous ruler of the Maurya Empire?", "Ashoka");
data.put("In which year did the Battle of Kalinga take place?", "261 BCE");
data.put("Who founded the Gupta Empire?", "Sri Gupta");
data.put("Who is known as the Napoleon of India?", "Samudragupta");
data.put("Who is known as the father of Indian archaeology?", "Alexander Cunningham");
data.put("Who was the founder of the Mughal Empire?", "Babur");
data.put("In which year did the Battle of Panipat take place?", "1526");
data.put("Which Mughal emperor built the Taj Mahal?", "Shah Jahan");
data.put("Who was the last Mughal Emperor?", "Bahadur Shah Zafar");
data.put("Who built the Red Fort?", "Shah Jahan");
data.put("Who built the Qutub Minar?", "Qutb-ud-din Aibak");
data.put("Who built the Charminar?", "Muhammad Quli Qutb Shah");
data.put("In which year did Vasco da Gama reach India?", "1498");
data.put("Who founded the Indian National Congress?", "A. O. Hume");
data.put("In which year was the Indian National Congress founded?", "1885");
data.put("Who was the first woman President of the Indian National Congress?", "Annie Besant");
data.put("Who was the first Indian woman President of the Indian National Congress?", "Sarojini Naidu");
data.put("Who gave the slogan Quit India?", "Mahatma Gandhi");
data.put("When did the Non-Cooperation Movement start?", "1920");
data.put("When did the Civil Disobedience Movement start?", "1930");
data.put("When did the Quit India Movement start?", "1942");
data.put("Who started the Swadeshi Movement?", "Bal Gangadhar Tilak");
data.put("Who started the Home Rule Movement in India?", "Annie Besant");
data.put("Who founded the Arya Samaj?", "Swami Dayananda Saraswati");
data.put("Who founded the Brahmo Samaj?", "Raja Ram Mohan Roy");
data.put("Who founded the Ramakrishna Mission?", "Swami Vivekananda");
data.put("Who wrote the book Arthashastra?", "Chanakya");
data.put("Who wrote the book Indica?", "Megasthenes");
data.put("Who wrote the book Discovery of India?", "Jawaharlal Nehru");
data.put("Who wrote the book Hind Swaraj?", "Mahatma Gandhi");
data.put("Who wrote the book Annihilation of Caste?", "B. R. Ambedkar");
data.put("Who was the first Governor-General of independent India?", "Lord Mountbatten");
data.put("Who was the first Indian Governor-General?", "C. Rajagopalachari");
data.put("Who was the first President of India?", "Dr. Rajendra Prasad");
data.put("Who was the first Prime Minister of India?", "Jawaharlal Nehru");
data.put("Which act is known as the Black Act?", "Rowlatt Act");
data.put("In which year did Jallianwala Bagh Massacre take place?", "1919");
data.put("Who was the Viceroy during Jallianwala Bagh?", "Lord Chelmsford");
data.put("Who led the Dandi March with Gandhi?", "Sarojini Naidu");
data.put("Which movement is also called White Revolution?", "Operation Flood");
data.put("Who is known as the Milkman of India?", "Dr. Verghese Kurien");
data.put("Where did the Revolt of 1857 begin?", "Meerut");
data.put("Who was the first martyr of the Revolt of 1857?", "Mangal Pandey");
data.put("Who led the revolt in Lucknow?", "Begum Hazrat Mahal");
data.put("Who led the revolt in Jhansi?", "Rani Lakshmibai");
data.put("Who led the revolt in Kanpur?", "Nana Sahib");
data.put("Who was the Governor-General during 1857 revolt?", "Lord Canning");
data.put("Which reformer is known as the Father of Modern India?", "Raja Ram Mohan Roy");
data.put("Who wrote the book Gita Rahasya?", "Bal Gangadhar Tilak");
data.put("Who gave the slogan Jai Jawan Jai Kisan?", "Lal Bahadur Shastri");
data.put("Who was the first woman ruler of Delhi?", "Razia Sultana");
data.put("Who built the Khajuraho temples?", "Chandela Dynasty");
data.put("Who built the Sun Temple at Konark?", "Narasimhadeva I");
data.put("Which empire is known as the Golden Age of India?", "Gupta Empire");
data.put("Who was the founder of the Chola Dynasty?", "Vijayalaya Chola");
data.put("Which king built the Brihadeeswara Temple?", "Rajaraja Chola I");
data.put("Who established the Slave Dynasty?", "Qutb-ud-din Aibak");
data.put("Who was the first Sultan of Delhi?", "Qutb-ud-din Aibak");
data.put("Who built the Ibādat Khāna?", "Akbar");
data.put("Who translated the Mahabharata into Persian?", "Akbar");
data.put("Who wrote Akbarnama?", "Abul Fazl");
data.put("Who was known as Zinda Pir?", "Aurangzeb");
data.put("Who was the founder of the Sikh Empire?", "Maharaja Ranjit Singh");
data.put("Who founded the Mauryan Empire?", "Chandragupta Maurya");
data.put("Who was the first ruler to unite most of India?", "Ashoka");
data.put("Where did Buddha attain enlightenment?", "Bodh Gaya");
data.put("Where did Buddha give his first sermon?", "Sarnath");
data.put("Where did Buddha die?", "Kushinagar");
data.put("Who was the founder of Buddhism?", "Gautama Buddha");
data.put("Who was the founder of Jainism?", "Mahavira");
data.put("What is the holy book of Jainism?", "Agamas");
data.put("Who founded the Vijayanagara Empire?", "Harihara and Bukka");
data.put("Who was the greatest ruler of Vijayanagara?", "Krishnadevaraya");
data.put("Who was known as the Lion of Punjab?", "Lala Lajpat Rai");
data.put("Who gave the slogan Inquilab Zindabad?", "Bhagat Singh");
data.put("Who gave the slogan Swaraj is my birthright?", "Bal Gangadhar Tilak");
data.put("Who founded Banaras Hindu University?", "Madan Mohan Malaviya");
data.put("Who is known as the Grand Old Man of India?", "Dadabhai Naoroji");
data.put("Who wrote Poverty and Un-British Rule in India?", "Dadabhai Naoroji");
data.put("What was the real name of Rani Lakshmibai?", "Manikarnika");
data.put("Which movement was launched after the Chauri Chaura incident?", "Civil Disobedience Movement");
data.put("Which Viceroy partitioned Bengal?", "Lord Curzon");
data.put("Who introduced Doctrine of Lapse?", "Lord Dalhousie");
data.put("Who introduced Permanent Settlement?", "Lord Cornwallis");
data.put("Who was the first Indian to pass ICS?", "Satyendranath Tagore");
data.put("Who formed the Forward Bloc?", "Subhas Chandra Bose");
data.put("Where was the Azad Hind Fauj formed?", "Singapore");
data.put("Who was called Frontier Gandhi?", "Khan Abdul Ghaffar Khan");
data.put("Who established the Prarthana Samaj?", "Atmaram Pandurang");
data.put("Who started the Aligarh Movement?", "Sir Syed Ahmed Khan");
data.put("Who built Fatehpur Sikri?", "Akbar");
data.put("Who built the Buland Darwaza?", "Akbar");
data.put("Who built the Jama Masjid in Delhi?", "Shah Jahan");
data.put("When was the Battle of Buxar fought?", "1764");
data.put("When was the Battle of Plassey fought?", "1757");
data.put("Who was the Viceroy during the partition of India?", "Lord Mountbatten");
data.put("Which act introduced Dyarchy in India?", "Government of India Act 1919");
data.put("Which act introduced Provincial Autonomy?", "Government of India Act 1935");
data.put("When was the Indian Constitution adopted?", "26 November 1949");


//1. General Study Tips

data.put("how to study effectively?", "Study in short sessions, revise regularly, and practice active recall. Avoid distractions and take proper breaks.");
data.put("give me study tips?", "Use a timetable, follow the Pomodoro technique, revise weekly, and test yourself with quizzes.");
data.put("how to concentrate while studying?", "Keep your phone away, study in a clean place, take breaks, and avoid multitasking.");
data.put("how to avoid distractions while studying?", "Turn off notifications, use airplane mode, and study in a quiet place.");
data.put("how can i increase my memory?", "Use active recall, spaced repetition, proper sleep, and regular revision.");


//Motivation / Productivity Suggestions
data.put("give me motivation to study?", "Start small, stay consistent, and remember your goals. Every small step counts!");
data.put("i am feeling lazy to study", "Start with just 10 minutes. Once you begin, your mind will get into study mode.");
data.put("how to stay consistent?", "Set daily goals, track progress, and reward yourself after completing study sessions.");
data.put("give me a study suggestion", "Focus on one topic at a time, revise repeatedly, and stay disciplined.");


//Time Management Tips

data.put("how to manage study time?", "Use a timetable, follow 45 minutes study and 15 minutes break, and prioritize difficult subjects first.");
data.put("give me time management tips", "Plan your day, set deadlines, break big tasks into smaller goals, and avoid multitasking.");


//Exam Preparation Suggestions

data.put("how to prepare for exams?", "Revise daily, solve previous papers, practice MCQs, and clear basic concepts.");
data.put("how to study for upsc?", "Focus on NCERTs, read newspapers daily, revise regularly, and practice mock tests.");
data.put("how to improve gk?", "Read newspapers, follow monthly current affairs, and revise GK lists daily.");

//Stress Management

data.put("i am stressed about studies", "Take a short walk, breathe deeply, and continue with small study sessions.");
data.put("how to reduce exam fear?", "Prepare early, revise daily, practice mock tests, and stay confident.");

// 50 STUDY SUGGESTIONS FOR YOUR BOT

data.put("give me study tips?", "Study in short sessions and revise regularly.");
data.put("how to study effectively?", "Focus for 45 minutes and take a 15 minute break.");
data.put("how to concentrate while studying?", "Keep your phone away and study in a quiet room.");
data.put("how to avoid distractions?", "Turn off notifications and block social media.");
data.put("how to manage study time?", "Create a timetable and stick to it daily.");
data.put("how to improve memory?", "Use active recall and spaced repetition.");
data.put("how to stay consistent in studies?", "Set small daily goals and follow them.");
data.put("give me study motivation?", "Start with small tasks and build momentum.");
data.put("how to prepare for exams?", "Revise daily and practice previous papers.");
data.put("how to improve gk?", "Read newspapers and revise GK lists daily.");
data.put("how to improve reading skills?", "Read 20 minutes daily without distraction.");
data.put("how to improve writing speed?", "Practice writing one page every day.");
data.put("how to avoid exam tension?", "Prepare early and revise regularly.");
data.put("how to plan my study day?", "Study difficult topics first, easy ones later.");
data.put("how to study for long hours?", "Take breaks and drink enough water.");
data.put("how to focus on study?", "Remove distractions and keep your desk clean.");
data.put("give me a study suggestion", "Break big topics into small parts.");
data.put("how to revise fast?", "Make short notes and revise them repeatedly.");
data.put("how to remember what I study?", "Teach the topic to someone else.");
data.put("how to stop procrastinating?", "Start studying for just 10 minutes.");
data.put("what is the best study method?", "Active recall is the most effective method.");
data.put("how to improve concentration?", "Meditate for 5 minutes before studying.");
data.put("how to get good marks?", "Revise regularly and solve mock tests.");
data.put("how to reduce stress?", "Take short walks and breathe deeply.");
data.put("how to stay disciplined?", "Study at the same time every day.");
data.put("what is the best time to study?", "Morning time is the most productive.");
data.put("how to build confidence in study?", "Practice daily and track your progress.");
data.put("how to improve mathematics?", "Practice problems every day.");
data.put("how to avoid forgetting?", "Revise after 1 day, 3 days, and 7 days.");
data.put("how to increase study speed?", "Practice solving questions with a timer.");
data.put("how to create a good timetable?", "Balance study, revision, and breaks.");
data.put("how to learn fast?", "Understand concepts instead of memorizing.");
data.put("how to study without getting bored?", "Change subjects every 1–2 hours.");
data.put("how to stay motivated?", "Remember your goals and future success.");
data.put("how to handle difficult subjects?", "Study them when your mind is fresh.");
data.put("how to top the exam?", "Focus on accuracy, revision, and practice.");
data.put("how to score full marks?", "Write clearly and revise multiple times.");
data.put("how to improve english?", "Read newspapers and speak daily.");
data.put("how to prepare for competitive exams?", "Solve mock tests daily.");
data.put("what should I do when I feel sleepy?", "Take a 10 minute break or drink water.");
data.put("how to make learning interesting?", "Use videos, diagrams, and real examples.");
data.put("how to study when I feel lazy?", "Start with an easy topic to warm up.");
data.put("how to manage multiple subjects?", "Study 2–3 subjects every day.");
data.put("how to avoid last minute tension?", "Complete syllabus early and revise weekly.");
data.put("how to keep my mind calm?", "Avoid overthinking and take proper rest.");
data.put("how to study fast and remember?", "Use short notes and active recall.");
data.put("how to stay positive during exams?", "Believe in your preparation and stay calm.");
data.put("how to study smart?", "Focus on important topics and revise repeatedly.");
data.put("how to complete syllabus on time?", "Follow a fixed schedule daily.");

// HEALTH TIPS

data.put("give me health tips?", "Drink plenty of water, sleep well, and eat balanced meals.");
data.put("how to stay healthy?", "Eat nutritious food, stay active, sleep 7–8 hours.");
data.put("how to improve immunity?", "Eat fruits, drink warm water, and stay hydrated.");
data.put("what should i eat for good health?", "Eat vegetables, fruits, whole grains, and protein.");
data.put("how to avoid junk food?", "Replace junk with fruits and nuts.");
data.put("how to stay fit?", "Exercise 30 minutes every day.");
data.put("how much water should i drink?", "Drink at least 2–3 liters daily.");
data.put("how to reduce stress?", "Practice breathing exercises and meditation.");
data.put("how to stay energetic?", "Eat small meals and get proper sleep.");
data.put("how to sleep better?", "Avoid phones before sleeping and maintain regular sleep time.");
data.put("how to maintain good hygiene?", "Bath daily, wash hands, and keep surroundings clean.");
data.put("how to avoid sickness?", "Eat healthy, drink water, and maintain hygiene.");
data.put("how to improve digestion?", "Eat slowly and include fiber in your diet.");
data.put("how to reduce screen time?", "Take breaks and follow the 20-20-20 rule.");
data.put("how to protect my eyes?", "Blink often and reduce screen brightness.");
data.put("how to avoid dehydration?", "Drink water regularly throughout the day.");
data.put("how to boost brain health?", "Sleep well, eat almonds, and study calmly.");
data.put("how to avoid headaches?", "Stay hydrated and avoid stress.");
data.put("how to stay active during studies?", "Take short breaks and stretch every hour.");
data.put("what is a healthy morning habit?", "Drink warm water and eat a light breakfast.");
data.put("how to avoid fatigue?", "Stay hydrated and get enough rest.");
data.put("how to keep my skin healthy?", "Drink water and avoid oily foods.");
data.put("how to maintain strong bones?", "Include milk, calcium, and sunlight exposure.");
data.put("how to improve lung health?", "Breathe fresh air and avoid pollution.");
data.put("how to improve stamina?", "Do regular walking or running.");
data.put("how to stay mentally strong?", "Meditate and talk to supportive people.");
data.put("how to keep my heart healthy?", "Avoid junk and exercise regularly.");
data.put("how to avoid obesity?", "Exercise daily and control sugar intake.");
data.put("how to eat healthy while studying?", "Choose fruits, nuts, and home-cooked food.");
data.put("how to improve metabolism?", "Drink warm water and walk daily.");
data.put("how to avoid overeating?", "Eat slowly and drink water before meals.");
data.put("how to reduce laziness?", "Sleep well and start your day with simple exercise.");
data.put("how to maintain good posture?", "Sit straight and avoid long screen hours.");
data.put("how to stay fresh all day?", "Hydrate and take small breaks.");
data.put("how to avoid fever?", "Boost immunity and follow hygiene.");
data.put("how to eat a balanced diet?", "Include carbs, protein, fat, vitamins, and minerals.");
data.put("how to avoid stress eating?", "Drink water and take a short walk instead.");
data.put("how to relax my mind?", "Practice deep breathing for 2 minutes.");
data.put("how to avoid eye strain?", "Follow the 20-20-20 screen rule.");
data.put("how to avoid back pain?", "Sit straight and take stretching breaks.");
data.put("how to clean my body internally?", "Drink warm water and eat fiber-rich foods.");
data.put("how to maintain healthy habits?", "Be consistent with sleep, diet, and exercise.");
data.put("how to avoid cold and cough?", "Cover yourself well and avoid chilled drinks.");
data.put("how to improve my mood?", "Listen to soft music and take a short walk.");
data.put("how to start a healthy lifestyle?", "Wake up early, drink water, and exercise.");
data.put("how to boost my confidence?", "Stay healthy, practice positivity, and sleep well.");
data.put("how to avoid tiredness?", "Stay hydrated and eat iron-rich foods.");
data.put("how to stay calm?", "Close your eyes and breathe deeply for one minute.");


// MOTIVATIONAL QUOTES

data.put("give me a motivational quote", "Believe you can, and you're halfway there.");
data.put("motivate me", "Success is the result of hard work and consistency.");
data.put("i need motivation", "Your only limit is your mind.");
data.put("i feel low", "Every day is a new beginning. Take a deep breath and start again.");
data.put("give me inspiration", "Dream big, stay positive, work hard, and enjoy the journey.");
data.put("inspire me", "The future depends on what you do today.");
data.put("i am tired", "Rest if you must, but don't quit.");
data.put("i feel like giving up", "Winners are not those who never fail, but those who never quit.");
data.put("i am stressed", "Calm your mind. You are stronger than your struggles.");
data.put("give me energy", "Push yourself, because no one else will do it for you.");
data.put("study motivation", "Small steps every day lead to big progress.");
data.put("exam motivation", "Do your best today; your future self will thank you.");
data.put("hardwork quote", "Hard work beats talent when talent doesn’t work hard.");
data.put("success quote", "Success is built on daily discipline and determination.");
data.put("positive quote", "Stay positive, work hard, and make it happen.");
data.put("life quote", "Life is 10% what happens to us and 90% how we react.");
data.put("encourage me", "You are capable of amazing things.");
data.put("boost me", "Don’t stop when you’re tired. Stop when you're done.");
data.put("i need confidence", "Believe in yourself and you will be unstoppable.");
data.put("push me", "The secret of getting ahead is getting started.");
data.put("give me strength", "Difficult roads often lead to beautiful destinations.");
data.put("motivation please", "Great things take time. Keep going.");
data.put("uplift me", "Stars can't shine without darkness.");
data.put("quote of the day", "Your growth begins the moment you decide to improve.");
data.put("give me strength to study", "Focus on progress, not perfection.");
data.put("help me study", "Success is the sum of small efforts repeated daily.");
data.put("i feel lazy", "You don’t have to be great to start, but you must start to be great.");
data.put("i feel unproductive", "Every minute you waste is a minute you never get back.");
data.put("motivate for upsc", "UPSC is not about intelligence; it's about discipline.");
data.put("motivate for exams", "Your hard work today creates your success tomorrow.");
data.put("boost my confidence", "Trust yourself. You know more than you think you do.");
data.put("encourage my studies", "Consistency is more important than speed.");
data.put("motivate my mind", "The best view comes after the hardest climb.");
data.put("i feel stressed", "Relax. It’s just a bad day, not a bad life.");
data.put("i feel hopeless", "Every storm runs out of rain. Better days are coming.");
data.put("how to stay strong", "Strength grows in moments when you think you can’t go on but keep going anyway.");
data.put("i need hope", "Where there is hope, there is strength.");
data.put("i need courage", "Courage is not the absence of fear; it’s the triumph over it.");
data.put("i am scared", "Do the thing you fear, and the fear will disappear.");
data.put("i feel pressure", "One step at a time. You are doing your best.");
data.put("give me wisdom", "The only impossible journey is the one you never begin.");
data.put("study inspiration", "Your dreams don’t work unless you do.");
data.put("push me to study", "Discipline now means freedom later.");
data.put("give me a powerful quote", "The pain you feel today will be the strength you feel tomorrow.");
data.put("uplift my mood", "Keep going. Everything you need will come at the right time.");
data.put("i want motivation", "Don't wait for opportunity. Create it.");
data.put("i want a quote", "Success starts with believing in yourself.");
data.put("i want study motivation", "If you get tired, learn to rest, not to quit.");
data.put("give me something positive", "Focus on the step in front of you, not the whole staircase.");
data.put("introduce yourself", "Hello! I'm Infiniq, your smart chatbot assistant.");
data.put("who are you", "I am Infiniq, here to help you learn and explore.");
data.put("tell me about you", "I'm Infiniq, a friendly AI created to assist you anytime.");
data.put("your introduction", "Hi! I'm Infiniq. Ask me anything, I'm ready!");
data.put("introduce u", "Hey there! I'm Infiniq, your AI study assistant.");
data.put("what is your introduction", "I'm Infiniq, an intelligent chatbot built to support your learning.");
data.put("give your intro", "Hi, I'm Infiniq—a chatbot designed to answer your questions and guide you.");
data.put("say your intro", "Hello! I am Infiniq, your virtual learning partner.");
data.put("can you introduce yourself", "Sure! I'm Infiniq, your helpful AI companion.");
data.put("introduce", "Hey! Infiniq here. Ready to assist you anytime!");
data.put("tell about yourself", "I'm Infiniq, an AI chatbot built to make learning easy and fun.");
data.put("who r u", "I'm Infiniq, your friendly chatbot assistant!");
data.put("your bio", "I'm Infiniq, an AI made to answer questions and motivate you.");
data.put("say about you", "I'm Infiniq, always ready to help with knowledge and support.");
data.put("what can you do", "I am Infiniq. I can answer questions, motivate you, and assist your learning.");
data.put("hi", "Hello! How can I assist you today?");
data.put("hello", "Hi there! How can I help?");
data.put("hey", "Hey! What can I do for you?");
data.put("introduce", "Hey! I'm Infiniq, your personal assistant chatbot!");
data.put("who are you", "I'm Infiniq – a smart chatbot built to help you!");
data.put("i feel stressed", "Relax. It's just a bad day, not a bad life.");
data.put("i am sad", "It's okay to feel sad. I'm here for you.");
data.put("how are you", "I'm functioning at 100%! How about you?");
data.put("help", "Sure! Tell me what you need help with.");
data.put("what can you do", "I can answer questions, motivate you, help study and more!");

    }

    public Map<String, String> getAll() {
        return data;
    }
}
